# Generated by Django 3.0.5 on 2020-05-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Librarian',
            new_name='librarian',
        ),
    ]
