# Generated by Django 3.0.5 on 2020-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20200502_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='addredd',
            new_name='address',
        ),
    ]
